const KEYCHAIN_STATE_OFF = 0
const KEYCHAIN_STATE_ON = 1
const MAX_PASSWORD_LENGTH_BYTES = 64;
const PBKDF2_SALT = "10000000"
const KEY_NONCES = {
	HMAC_SECRET: "HMAC SECRET", 
	GCM_SECRET: "GCM SECRET", 
	AUTH_SECRET: "AUTH SECRET",
};
module.exports = {
	KEYCHAIN_STATE_OFF,
	KEYCHAIN_STATE_ON,
	MAX_PASSWORD_LENGTH_BYTES,
	PBKDF2_SALT,
	KEY_NONCES
}